apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-db
  labels:
    app: my-db
spec:
  serviceName: my-db-svc
  replicas: 2
  podManagementPolicy: OrderedReady
  updateStrategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: my-db
        image: cassandra:4.1.0
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        env:

          - name: CASSANDRA_CLUSTER_NAME
            value: "cluster1"
          - name: CASSANDRA_DC
            value: "dc1"
          - name: CASSANDRA_RACK
            value: "rack1"
          - name: CASSANDRA_SEEDS
            value: "my-db-0.my-db-svc.default.svc.cluster.local"

        volumeMounts:
        - name: my-db-pvc
          mountPath: /var/lib/cassandra
  volumeClaimTemplates:
  - metadata:
      name: my-db-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi