apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-db
  labels:
    app: my-db
spec:
  serviceName: my-db-svc
  replicas: 2
  podManagementPolicy: OrderedReady
  updateStrategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: my-db
        image: cassandra:latest
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        # resources:
        #   limits:
        #     cpu: '1'
        #     memory: 1Gi
        #   requests:
        #     cpu: "500m"
        #     memory: 500Mi
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        env:
          #- name: MAX_HEAP_SIZE
          #  value: 512M
          #- name: HEAP_NEWSIZE
          #  value: 100M
          - name: CASSANDRA_CLUSTER_NAME
            value: "cluster1"
          - name: CASSANDRA_DC
            value: "dc1"
          - name: CASSANDRA_RACK
            value: "rack1"
          - name: CASSANDRA_SEEDS
            value: "my-db-0.my-db-svc.default.svc.cluster.local"
          #- name: CASSANDRA_ENDPOINT_SNITCH
            #value: "GossipingPropertyFileSnitch"
        #readinessProbe:
        #  exec:
        #    command:
        #    - /bin/bash
        #    - -c
        #    - /ready-probe.sh
        #  initialDelaySeconds: 15
        #  timeoutSeconds: 5
        volumeMounts:
        - name: my-db-pvc
          mountPath: /var/lib/cassandra
  volumeClaimTemplates:
  - metadata:
      name: my-db-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi