apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybackend
  labels:
    app: mybackend
spec:
  template:
    metadata:
      name: mybackend
      labels:
        app: mybackend
    spec:
      setHostnameAsFQDN: true
      containers:
      - name: mybackend
        image: docker.io/rustybridge/mybackend
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: listen
  selector:
    matchLabels:
      app: mybackend
  replicas: 2


